/*
Apache2 License Notice
Copyright 2017 Alex Barry

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#ifndef SRC_EVENT_INTERFACE_EVENT_INTERFACE_H_
#define SRC_EVENT_INTERFACE_EVENT_INTERFACE_H_

namespace Scui {

//! Un-assigned Event Type
const int NULL_EVENT = -1;

//! Mouse Event Type
const int MOUSE_EVENT = 0;

//! Keyboard Event Type
const int KEYBOARD_EVENT = 1;

//! Un-assigned Modifier
const int NULL_MODIFIER = -1;

//! Shift Modifier
const int SHIFT_MODIFIER = 1;

//! Control Modifier
const int CTRL_MODIFIER = 2;

//! Alt Modifier
const int ALT_MODIFIER = 4;

// An Event is generated by a Mouse/Keyboard event
class EventInterface {
 public:
  virtual ~EventInterface() {}
  //! Get the type of the Event
  virtual int get_type() = 0;
  //! Get the modifiers attached to the event
  virtual int get_modifiers() = 0;
};

}  // namespace Scui

#endif  // SRC_EVENT_INTERFACE_EVENT_INTERFACE_H_
