/*
Apache2 License Notice
Copyright 2017 Alex Barry

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#include "event_interface.h"
#include "input_event.h"

#ifndef SRC_EVENT_INTERFACE_KEYBOARD_EVENT_INTERFACE_H_
#define SRC_EVENT_INTERFACE_KEYBOARD_EVENT_INTERFACE_H_

namespace Scui {

// An InputEvent is generated by a Mouse/Keyboard event
class KeyboardEventInterface : public EventInterface {
 public:
  virtual ~KeyboardEventInterface() {}
  //! Get the key associated with the event
  virtual char get_key() = 0;
};

}  // namespace Scui

#endif  // SRC_EVENT_INTERFACE_KEYBOARD_EVENT_INTERFACE_H_
