sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - build-essential
    - cmake
    - libglew-dev
    - libglm-dev
    - libsoil-dev
install:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip
- unzip glfw-3.2.1.zip
- cd glfw-3.2.1 && cmake .
- cd $TRAVIS_BUILD_DIR
before_script:
- gcc --version
- ldd --version
script:
- make tests
- make examples
- sudo make install
- make clean
- make tests INCL_DIR=-I.
- make examples INCL_DIR=-I.
