sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
install:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- mkdir ../scui_deps
- sudo cp scripts/deb/build_deps.sh ../scui_deps
- cd ../scui_deps && sudo ./build_deps.sh
- cd $TRAVIS_BUILD_DIR
before_script:
- gcc --version
- ldd --version
script:
- make tests
- make examples
- sudo make install
- make clean
- make examples INCL_DIR=-I.
