/*
Apache2 License Notice
Copyright 2017 Alex Barry

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#include "input_event.h"
#include "interface/mouse_event_interface.h"

#ifndef SRC_EVENT_MOUSE_INPUT_EVENT_H_
#define SRC_EVENT_MOUSE_INPUT_EVENT_H_

namespace Scui {

// An InputEvent is generated by a Mouse/Keyboard event
class MouseInputEvent : public InputEvent, public MouseEventInterface {
  float _x = 0.0f;
  float _y = 0.0f;
  int _button = NULL_MOUSE_EVENT;

 public:
  MouseInputEvent(float x, float y, int button, int mods) : InputEvent(MOUSE_EVENT, mods) \
    {_x = x; _y = y; _button = button;}
  float get_x() {return _x;}
  float get_y() {return _y;}
  int get_button() {return _button;}
  int get_type() {return InputEvent::get_type();}
  int get_modifiers() {return InputEvent::get_modifiers();}
};

}  // namespace Scui

#endif  // SRC_EVENT_INCLUDE_MOUSE_INPUT_EVENT_H_
